spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banco_de_dados
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true


feign-client:
  url:
    api: https://deckofcardsapi.com/api
